// See https://aka.ms/new-console-template for more information
using SoSe2026_CS;
using SoSe26_CS;

//ArithmetischeOP.Start();
//LogischeOP.Start();
//Aufgabe1.Start();
//testlol.Start();
//Aufgabe2.Start();
//Variablen.Start();
//Aufgabe3.Start();
//Aufgabe4.Start();
//strOperationen.Start();
//AufgabeTeams.Start();
//Aufgabe5.Start();
//Eingabe.Start();
//CsBasicWHAufgaben.Start();
//WHAufgaben.Start1();
//WHAufgaben.Start2();
//WHAufgaben.Start3();
//WHAufgaben.Start4();
//Konvert.Start();
//Array_Test.Start();
//Aufgabe13.Start();
//Tafelaufgabe.Start();
//Kontrolle.Start();
//AufgabePaP.Start();
//PaP_Uebung.Start();
//Schulaufgabe1.Start();
//Aufgabe2_schleifen.start();
//Aufgabe3_Schleifen.Start();
//Aufgabe4_Schleifen.Start();
//SchleifenUndArrays.Start();
//AufgabeSchleifen2.Start();
//AufgabeSchleifen22.Start();
Aufgabe01_Wetterdaten.Start();
